dev:
    storage: local
    storage_path: ${HOME}/.fscap_cloud_test

test:
    storage: local
    storage_path: /tmp/test

prod:
    s3_access_key: _env:S3_ACCESS_KEY
    s3_secret_key: _env:S3_SECRET_KEY
    s3_bucket: _env:S3_BUCKET
    storage: s3
    storage_path: /prod
